version: "2"
services:
  requisition-batch-ui:
    image: openlmis/dev-ui:9.0.2-SNAPSHOT
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - requisition-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - requisition-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:6.2.2
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:5.6.1
    volumes:
      - '/openlmis-referencedata-ui'
  requisition-ui:
    image: openlmis/requisition-ui:7.0.1
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:2.0.5
    volumes:
      - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:7.2.1
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:5.1.5
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmismz/requisition-batch-ui
