version: "2"

services:
  requisition-batch-ui:
    image: openlmis/dev-ui:${OL_DEV_UI_VERSION}
    working_dir: /app
    volumes:
      - '.:/app'
    ports:
      - "9000:9000"
      - "9876:9876"
    env_file: .env
    volumes_from:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - requisition-ui
      - ui-components
      - ui-layout
    depends_on:
      - auth-ui
      - referencedata-ui
      - stockmanagement-ui
      - requisition-ui
      - ui-components
      - ui-layout
  auth-ui:
    image: openlmis/auth-ui:${OL_AUTH_UI_VERSION}
    volumes:
      - '/openlmis-auth-ui'
  referencedata-ui:
    image: openlmis/referencedata-ui:${OL_REFERENCEDATA_UI_VERSION}
    volumes:
      - '/openlmis-referencedata-ui'
  requisition-ui:
    image: openlmis/requisition-ui:${OL_REQUISITION_UI_VERSION}
    volumes:
      - '/openlmis-requisition-ui'
  stockmanagement-ui:
    image: openlmis/stockmanagement-ui:${OL_STOCKMANAGEMENT_UI_VERSION}
    volumes:
      - '/openlmis-stockmanagement-ui'
  ui-components:
    image: openlmis/ui-components:${OL_UI_COMPONENTS_VERSION}
    volumes:
      - '/openlmis-ui-components'
  ui-layout:
    image: openlmis/ui-layout:${OL_UI_LAYOUT_VERSION}
    volumes:
      - '/openlmis-ui-layout'
  image:
    build: .
    image: openlmismz/requisition-batch-ui
